# Generated by Django 3.2.12 on 2022-02-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='subs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
